export BUILT_PRODUCTS_DIR="/Users/pawel/Library/Developer/Xcode/DerivedData/tumitfahrer-fbahuqrhvawhpqfljxjkkrxdtjwh/Build/Intermediates/ArchiveIntermediates/tumitfahrer/BuildProductsPath/Release-iphoneos"
export CURRENT_ARCH="arm64"
export OBJECT_FILE_DIR_normal="/Users/pawel/Library/Developer/Xcode/DerivedData/tumitfahrer-fbahuqrhvawhpqfljxjkkrxdtjwh/Build/Intermediates/ArchiveIntermediates/tumitfahrer/IntermediateBuildFilesPath/tumitfahrer.build/Release-iphoneos/mitfahrer-app.build/Objects-normal"
export OBJROOT="/Users/pawel/Library/Developer/Xcode/DerivedData/tumitfahrer-fbahuqrhvawhpqfljxjkkrxdtjwh/Build/Intermediates/ArchiveIntermediates/tumitfahrer/IntermediateBuildFilesPath"
export SRCROOT="/Users/pawel/Documents/dev/Objective-C/tumitfahrer"
